# project.toml
[project]
id = "my-go-app"
name = "My Go App"
version = "0.1.0"

[[build.requires]]
uri = "urn:cnb:builder:paketo-buildpacks/go"

[[build.env]]
name = "BP_GO_TARGETS"
value = "./cmd/api"
