// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"encoding/json"
	"time"
)

type ActivityList struct {
	ID        int64     `json:"id"`
	TripOwner int64     `json:"trip_owner"`
	Activity  string    `json:"activity"`
	DateTime  time.Time `json:"date_time"`
	Checked   bool      `json:"checked"`
}

type EmergencyContact struct {
	ID          int64  `json:"id"`
	Owner       int64  `json:"owner"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}

type Itinerary struct {
	ID          int64     `json:"id"`
	Owner       int64     `json:"owner"`
	TakeOffDate time.Time `json:"take_off_date"`
	ReturnDate  time.Time `json:"return_date"`
	Destination string    `json:"destination"`
	CreatedAt   time.Time `json:"created_at"`
}

type TravelChecklist struct {
	ID        int64  `json:"id"`
	TripOwner int64  `json:"trip_owner"`
	ItemTask  string `json:"item_task"`
	Checked   bool   `json:"checked"`
}

type TripBooking struct {
	ID             int64  `json:"id"`
	TripOwner      int64  `json:"trip_owner"`
	BookingType    string `json:"booking_type"`
	BookingDetails string `json:"booking_details"`
}

type TripLog struct {
	ID        int64           `json:"id"`
	TripOwner int64           `json:"trip_owner"`
	Logs      json.RawMessage `json:"logs"`
}

type User struct {
	ID             int64     `json:"id"`
	Fullname       string    `json:"fullname"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	PhoneNumber    string    `json:"phone_number"`
	TripState      bool      `json:"trip_state"`
	CreatedAt      time.Time `json:"created_at"`
}
