// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (ActivityList, error)
	CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) (EmergencyContact, error)
	CreateTravelChecklist(ctx context.Context, arg CreateTravelChecklistParams) (TravelChecklist, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (Itinerary, error)
	CreateTripBooking(ctx context.Context, arg CreateTripBookingParams) (TripBooking, error)
	CreateTripLogs(ctx context.Context, arg CreateTripLogsParams) (TripLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActivity(ctx context.Context) error
	DeleteItinerary(ctx context.Context, owner int64) error
	DeleteTravelChecklist(ctx context.Context) error
	DeleteTripBooking(ctx context.Context) error
	DeleteTripLogs(ctx context.Context) error
	DeleteUser(ctx context.Context) error
	GetATripLogUpdate(ctx context.Context, tripOwner int64) (GetATripLogUpdateRow, error)
	GetActivityUpdate(ctx context.Context, tripOwner int64) (GetActivityUpdateRow, error)
	GetEmergencyContactUpdate(ctx context.Context, owner int64) (EmergencyContact, error)
	GetTravelChecklist(ctx context.Context, tripOwner int64) (GetTravelChecklistRow, error)
	GetTripBookingUpdate(ctx context.Context, tripOwner int64) (TripBooking, error)
	GetTripUpdate(ctx context.Context, owner int64) (GetTripUpdateRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, username string) (User, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error)
	ListTravelChecklist(ctx context.Context, arg ListTravelChecklistParams) ([]ListTravelChecklistRow, error)
	ListTripBooking(ctx context.Context, arg ListTripBookingParams) ([]ListTripBookingRow, error)
	ListTripLogs(ctx context.Context, arg ListTripLogsParams) ([]ListTripLogsRow, error)
	ListTrips(ctx context.Context, arg ListTripsParams) ([]ListTripsRow, error)
	ListsAccounts(ctx context.Context, arg ListsAccountsParams) ([]EmergencyContact, error)
}

var _ Querier = (*Queries)(nil)
